/**
 * Styling detectors module exports
 *
 * Detects styling and design system patterns.
 *
 * @requirements 9.1-9.8 - Styling pattern detection
 */

// Design tokens detector
export {
  DesignTokensDetector,
  createDesignTokensDetector,
  // Types
  type TokenPatternType,
  type HardcodedValueType,
  type TokenUsageInfo,
  type HardcodedValueInfo,
  type DesignTokenAnalysis,
  // Helper functions
  shouldExcludeFile,
  isAllowedHardcodedValue,
  detectTokenImports,
  detectCSSCustomProperties,
  detectThemeObjectUsage,
  detectHardcodedColors,
  detectHardcodedSpacing,
  analyzeDesignTokens,
  // Constants
  DESIGN_TOKEN_IMPORT_PATTERNS,
  CSS_CUSTOM_PROPERTY_PATTERN,
  THEME_OBJECT_PATTERNS,
  HARDCODED_COLOR_PATTERNS,
  HARDCODED_SPACING_PATTERNS,
  TOKEN_PROPERTIES,
  ALLOWED_HARDCODED_VALUES,
  EXCLUDED_FILE_PATTERNS,
} from './design-tokens.js';

// Spacing scale detector
export {
  SpacingScaleDetector,
  createSpacingScaleDetector,
  // Types
  type SpacingPatternType,
  type ArbitrarySpacingType,
  type SpacingPatternInfo,
  type ArbitrarySpacingInfo,
  type SpacingScaleAnalysis,
  // Helper functions
  shouldExcludeFile as shouldExcludeFileFromSpacing,
  isAllowedSpacingValue,
  isOn4pxScale,
  isOn8pxScale,
  isOnRemScale,
  findNearest4pxValue,
  findNearest8pxValue,
  findNearestRemValue,
  detectTailwindSpacing,
  detectTailwindArbitrarySpacing,
  detectCSSSpacingProperties,
  detectThemeSpacing,
  detectArbitraryPxSpacing,
  detectArbitraryRemSpacing,
  detectArbitraryEmSpacing,
  analyzeSpacingScale,
  // Constants
  SPACING_SCALE_4PX,
  SPACING_SCALE_8PX,
  SPACING_SCALE_REM,
  TAILWIND_SPACING_PATTERNS,
  TAILWIND_ARBITRARY_SPACING_PATTERN,
  CSS_SPACING_PROPERTY_PATTERN,
  THEME_SPACING_PATTERNS,
  HARDCODED_SPACING_PATTERNS as SPACING_HARDCODED_PATTERNS,
  SPACING_PROPERTIES,
  ALLOWED_SPACING_VALUES,
  EXCLUDED_FILE_PATTERNS as SPACING_EXCLUDED_FILE_PATTERNS,
} from './spacing-scale.js';

// Color usage detector
export {
  ColorUsageDetector,
  createColorUsageDetector,
  // Types
  type ColorPatternType,
  type HardcodedColorType,
  type ColorPatternInfo,
  type HardcodedColorInfo,
  type ColorUsageAnalysis,
  // Helper functions
  shouldExcludeFile as shouldExcludeFileFromColor,
  isAllowedHardcodedColor,
  detectCSSColorProperties,
  detectThemeColors,
  detectTailwindColors,
  detectNamedCSSColors,
  detectHardcodedColors as detectHardcodedColorValues,
  suggestColorToken,
  analyzeColorUsage,
  // Constants
  CSS_COLOR_PROPERTY_PATTERN,
  THEME_COLOR_PATTERNS,
  TAILWIND_COLOR_PATTERNS,
  HARDCODED_COLOR_PATTERNS as COLOR_HARDCODED_PATTERNS,
  NAMED_CSS_COLORS,
  COLOR_PROPERTIES,
  ALLOWED_HARDCODED_COLORS,
  EXCLUDED_FILE_PATTERNS as COLOR_EXCLUDED_FILE_PATTERNS,
} from './color-usage.js';

// Typography detector
export {
  TypographyDetector,
  createTypographyDetector,
  // Types
  type TypographyPatternType,
  type HardcodedTypographyType,
  type TypographyPatternInfo,
  type HardcodedTypographyInfo,
  type TypographyAnalysis,
  // Helper functions
  shouldExcludeFile as shouldExcludeFileFromTypography,
  isAllowedTypographyValue,
  isAllowedFontFamily,
  isOnTypographyScale,
  isOnLineHeightScale,
  isOnFontWeightScale,
  findNearestFontSize,
  findNearestLineHeight,
  findNearestFontWeight,
  detectCSSTypographyProperties,
  detectThemeTypography,
  detectTailwindTypography,
  detectTailwindArbitraryTypography,
  detectArbitraryFontSizes,
  detectArbitraryLineHeights,
  detectArbitraryFontWeights,
  detectHardcodedFontFamilies,
  suggestTypographyToken,
  analyzeTypography,
  // Constants
  TYPOGRAPHY_SCALE_PX,
  TYPOGRAPHY_SCALE_REM,
  LINE_HEIGHT_SCALE,
  FONT_WEIGHT_SCALE,
  CSS_TYPOGRAPHY_PROPERTY_PATTERN,
  THEME_TYPOGRAPHY_PATTERNS,
  TAILWIND_TYPOGRAPHY_PATTERNS,
  TAILWIND_ARBITRARY_TYPOGRAPHY_PATTERN,
  HARDCODED_FONT_SIZE_PATTERNS,
  HARDCODED_LINE_HEIGHT_PATTERN,
  HARDCODED_FONT_WEIGHT_PATTERN,
  HARDCODED_FONT_FAMILY_PATTERN,
  TYPOGRAPHY_PROPERTIES,
  ALLOWED_TYPOGRAPHY_VALUES,
  ALLOWED_FONT_FAMILIES,
  EXCLUDED_FILE_PATTERNS as TYPOGRAPHY_EXCLUDED_FILE_PATTERNS,
} from './typography.js';

// Class naming detector
export {
  ClassNamingDetector,
  createClassNamingDetector,
  // Types
  type ClassNamingPatternType,
  type ClassNamingViolationType,
  type ClassNamingPatternInfo,
  type ClassNamingViolationInfo,
  type ClassNamingAnalysis,
  // Helper functions
  shouldExcludeFile as shouldExcludeFileFromClassNaming,
  isBEMClassName,
  isTailwindUtilityClass,
  isSemanticClassName,
  isSMACSClassName,
  validateBEMClassName,
  detectBEMPatterns,
  detectUtilityFirstPatterns,
  detectCSSModulesPatterns,
  detectSemanticPatterns,
  detectSMACSPatterns,
  detectInvalidBEMPatterns,
  detectMixedConventions,
  suggestBEMFix,
  getDominantConvention,
  analyzeClassNaming,
  // Constants
  BEM_PATTERN,
  STRICT_BEM_PATTERN,
  INVALID_BEM_PATTERNS,
  TAILWIND_UTILITY_PATTERNS,
  CSS_MODULES_PATTERNS,
  SEMANTIC_NAMING_PATTERNS,
  SMACSS_PATTERNS,
  OOCSS_PATTERNS,
  EXCLUDED_FILE_PATTERNS as CLASS_NAMING_EXCLUDED_FILE_PATTERNS,
  UTILITY_CLASS_ORDER,
} from './class-naming.js';

// Tailwind patterns detector
export {
  TailwindPatternsDetector,
  createTailwindPatternsDetector,
  // Types
  type TailwindPatternType,
  type TailwindViolationType,
  type TailwindPatternInfo,
  type TailwindViolationInfo,
  type TailwindAnalysis,
  // Helper functions
  shouldExcludeFile as shouldExcludeFileFromTailwind,
  isTailwindUtilityClass as isTailwindUtilityClassFromTailwind,
  isArbitraryValueClass,
  hasResponsivePrefix,
  hasStateVariant,
  hasDarkModePrefix,
  extractBaseClass,
  getResponsiveBreakpoint,
  getBreakpointOrderIndex,
  detectUtilityClasses,
  detectArbitraryValues,
  detectResponsivePrefixes,
  detectStateVariants,
  detectDarkMode,
  detectApplyDirective,
  detectConfigCustomizations,
  detectArbitraryValueViolations,
  detectConflictingClasses,
  detectInconsistentBreakpointOrder,
  detectMixedArbitraryStandard,
  suggestStandardClass,
  analyzeTailwindPatterns,
  // Constants
  TAILWIND_UTILITY_PATTERNS as TAILWIND_PATTERNS_UTILITY,
  TAILWIND_ARBITRARY_VALUE_PATTERN,
  TAILWIND_RESPONSIVE_PREFIXES,
  TAILWIND_RESPONSIVE_PATTERN,
  TAILWIND_STATE_VARIANTS,
  TAILWIND_STATE_VARIANT_PATTERN,
  TAILWIND_DARK_MODE_PATTERN,
  TAILWIND_APPLY_PATTERN,
  TAILWIND_CONFIG_PATTERNS,
  CONFLICTING_CLASS_PAIRS,
  RESPONSIVE_BREAKPOINT_ORDER,
  CLASS_ORDER_CATEGORIES,
  EXCLUDED_FILE_PATTERNS as TAILWIND_EXCLUDED_FILE_PATTERNS,
} from './tailwind-patterns.js';

// Z-index scale detector
export {
  ZIndexScaleDetector,
  createZIndexScaleDetector,
  // Types
  type ZIndexPatternType,
  type ArbitraryZIndexType,
  type ZIndexPatternInfo,
  type ArbitraryZIndexInfo,
  type ZIndexScaleAnalysis,
  // Helper functions
  shouldExcludeFile as shouldExcludeFileFromZIndex,
  isAllowedZIndexValue,
  isOnZIndexScale,
  isOnExtendedZIndexScale,
  isMagicNumber,
  isHighMagicNumber,
  findNearestZIndexValue,
  suggestZIndexValue,
  detectTailwindZIndex,
  detectTailwindArbitraryZIndex,
  detectCSSZIndexProperties,
  detectThemeZIndex,
  detectCSSZIndexValues,
  analyzeZIndexScale,
  // Constants
  Z_INDEX_SCALE,
  Z_INDEX_SCALE_EXTENDED,
  SEMANTIC_Z_INDEX_VALUES,
  MAGIC_NUMBER_THRESHOLD,
  HIGH_MAGIC_NUMBER_THRESHOLD,
  TAILWIND_Z_INDEX_PATTERN,
  TAILWIND_ARBITRARY_Z_INDEX_PATTERN,
  CSS_Z_INDEX_PROPERTY_PATTERN,
  THEME_Z_INDEX_PATTERNS,
  CSS_Z_INDEX_VALUE_PATTERN,
  HARDCODED_Z_INDEX_PATTERN,
  ALLOWED_Z_INDEX_VALUES,
  EXCLUDED_FILE_PATTERNS as Z_INDEX_EXCLUDED_FILE_PATTERNS,
} from './z-index-scale.js';

// Responsive detector
export {
  ResponsiveDetector,
  createResponsiveDetector,
  // Types
  type ResponsivePatternType,
  type ResponsiveViolationType,
  type ResponsivePatternInfo,
  type ResponsiveViolationInfo,
  type ResponsiveAnalysis,
  // Helper functions
  shouldExcludeFile as shouldExcludeFileFromResponsive,
  isStandardBreakpoint,
  isAllowedBreakpointValue,
  getBreakpointOrderIndex as getResponsiveBreakpointOrderIndex,
  findNearestBreakpoint,
  suggestBreakpoint,
  convertToPixels,
  detectTailwindResponsive,
  detectCSSMediaQueriesMinWidth,
  detectCSSMediaQueriesMaxWidth,
  detectCSSContainerQueries,
  detectThemeBreakpoints,
  detectCSSBreakpointProperties,
  detectInconsistentBreakpointOrder as detectResponsiveInconsistentBreakpointOrder,
  detectMixedApproach,
  detectArbitraryBreakpoints,
  analyzeResponsive,
  // Constants
  TAILWIND_BREAKPOINTS,
  TAILWIND_BREAKPOINT_ORDER,
  COMMON_BREAKPOINTS,
  TAILWIND_RESPONSIVE_PATTERN as RESPONSIVE_TAILWIND_PATTERN,
  CSS_MEDIA_QUERY_MIN_WIDTH_PATTERN,
  CSS_MEDIA_QUERY_MAX_WIDTH_PATTERN,
  CSS_CONTAINER_QUERY_PATTERN,
  THEME_BREAKPOINT_PATTERNS,
  CSS_BREAKPOINT_PROPERTY_PATTERN,
  HARDCODED_MEDIA_QUERY_PATTERN,
  EXCLUDED_FILE_PATTERNS as RESPONSIVE_EXCLUDED_FILE_PATTERNS,
  ALLOWED_BREAKPOINT_VALUES,
} from './responsive.js';
